services:
  qc.fair_crabby-fuchsia-rattlesnake:
    command: sleep 6000000
    image: ferag/fair_eva:fair
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
